version: '3.8'

services:
  mongodb:
    image : mongo:5.0.8-focal
    container_name: mongodb
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./conf/db01/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/db01:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null

  redis:
    image: 'redis:6.2.13'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./conf/redis01:/opt/redis-conf
      - ./conf/redis01/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis01:/data
    ports:
      - '6379:6379'
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    image: nginx:stable
    volumes:
      - ./api-gateway-local/conf.d:/etc/nginx/conf.d
      - ./web/html:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - app0-admin-api
      - app0-app1-api
      - app0-app2-api
      - app0-app3-api
      - app0-app4-api
      - app0-app5-api
      - app0-app6-api

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - storage1:/data
    command: server --console-address ":9001" /data

  app0-admin-api:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-admin:0.3.7
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app0-log-hopeit:/var/log/hopeit
      - app0-secrets:/app/.secrets
    environment:
      REDIS_URL: ${REDIS_URL}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_PATH: ${LOGS_PATH}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      APP0_ADMIN_API_URL: ${APP0_ADMIN_API_URL}
      APP0_ADMIN_URL: ${APP0_ADMIN_URL}
      MAIL_APP_FROM: ${MAIL_APP_FROM}
      OBJECT_STORAGE_ACCESS_KEY_ID: ${OBJECT_STORAGE_ACCESS_KEY_ID}
      OBJECT_STORAGE_SECRET_ACCESS_KEY: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
      OBJECT_STORAGE_ENDPOINT_URL: ${OBJECT_STORAGE_ENDPOINT_URL}
      OBJECT_STORAGE_SSL: ${OBJECT_STORAGE_SSL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DOMAIN: ${DOMAIN}
      PYTHONUNBUFFERED: 1
    ports:
      - 8021:8021

  app0-admin-ui:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-admin-ui:0.3.1
    ports:
      - '8081:80'
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./conf/admin-ui/default.conf:/etc/nginx/conf.d/default.conf

  app0-app1-api:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app1:0.2.1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app0-log-hopeit:/var/log/hopeit
      - app0-secrets:/app0-admin/.secrets
    environment:
      REDIS_URL: ${REDIS_URL}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_PATH: ${LOGS_PATH}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      APP0_ADMIN_API_URL: ${APP0_ADMIN_API_URL}
      APP0_ADMIN_URL: ${APP0_ADMIN_URL}
      OBJECT_STORAGE_ACCESS_KEY_ID: ${OBJECT_STORAGE_ACCESS_KEY_ID}
      OBJECT_STORAGE_SECRET_ACCESS_KEY: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
      OBJECT_STORAGE_ENDPOINT_URL: ${OBJECT_STORAGE_ENDPOINT_URL}
      OBJECT_STORAGE_SSL: ${OBJECT_STORAGE_SSL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DOMAIN: ${DOMAIN}
      PYTHONUNBUFFERED: 1
    ports:
      - 8022:8022

  app0-app1-ui:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app1-ui:0.3.0
    ports:
      - '8082:80'
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./conf/app1-ui/default.conf:/etc/nginx/conf.d/default.conf

  app0-app2-api:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app2:0.2.1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app0-log-hopeit:/var/log/hopeit
      - app0-secrets:/app0-admin/.secrets
    environment:
      REDIS_URL: ${REDIS_URL}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_PATH: ${LOGS_PATH}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      APP0_ADMIN_API_URL: ${APP0_ADMIN_API_URL}
      APP0_ADMIN_URL: ${APP0_ADMIN_URL}
      OBJECT_STORAGE_ACCESS_KEY_ID: ${OBJECT_STORAGE_ACCESS_KEY_ID}
      OBJECT_STORAGE_SECRET_ACCESS_KEY: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
      OBJECT_STORAGE_ENDPOINT_URL: ${OBJECT_STORAGE_ENDPOINT_URL}
      OBJECT_STORAGE_SSL: ${OBJECT_STORAGE_SSL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DOMAIN: ${DOMAIN}
      PYTHONUNBUFFERED: 1
    ports:
      - 8023:8023

  app0-app2-ui:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app2-ui:0.3.0
    ports:
      - '8083:80'
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./conf/app2-ui/default.conf:/etc/nginx/conf.d/default.conf

  app0-app3-api:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app3:0.2.1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app0-log-hopeit:/var/log/hopeit
      - app0-secrets:/app0-admin/.secrets
    environment:
      REDIS_URL: ${REDIS_URL}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_PATH: ${LOGS_PATH}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      APP0_ADMIN_API_URL: ${APP0_ADMIN_API_URL}
      APP0_ADMIN_URL: ${APP0_ADMIN_URL}
      OBJECT_STORAGE_ACCESS_KEY_ID: ${OBJECT_STORAGE_ACCESS_KEY_ID}
      OBJECT_STORAGE_SECRET_ACCESS_KEY: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
      OBJECT_STORAGE_ENDPOINT_URL: ${OBJECT_STORAGE_ENDPOINT_URL}
      OBJECT_STORAGE_SSL: ${OBJECT_STORAGE_SSL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DOMAIN: ${DOMAIN}
      PYTHONUNBUFFERED: 1
    ports:
      - 8024:8024

  app0-app3-ui:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app3-ui:0.3.0
    ports:
      - '8084:80'
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./conf/app3-ui/default.conf:/etc/nginx/conf.d/default.conf

  app0-app4-api:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app4:0.2.1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app0-log-hopeit:/var/log/hopeit
      - app0-secrets:/app0-admin/.secrets
    environment:
      REDIS_URL: ${REDIS_URL}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_PATH: ${LOGS_PATH}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      APP0_ADMIN_API_URL: ${APP0_ADMIN_API_URL}
      APP0_ADMIN_URL: ${APP0_ADMIN_URL}
      OBJECT_STORAGE_ACCESS_KEY_ID: ${OBJECT_STORAGE_ACCESS_KEY_ID}
      OBJECT_STORAGE_SECRET_ACCESS_KEY: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
      OBJECT_STORAGE_ENDPOINT_URL: ${OBJECT_STORAGE_ENDPOINT_URL}
      OBJECT_STORAGE_SSL: ${OBJECT_STORAGE_SSL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DOMAIN: ${DOMAIN}
      PYTHONUNBUFFERED: 1
    ports:
      - 8025:8025

  app0-app4-ui:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app4-ui:0.3.0
    ports:
      - '8085:80'
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./conf/app4-ui/default.conf:/etc/nginx/conf.d/default.conf

  app0-app5-api:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app5:0.4.6
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app0-log-hopeit:/var/log/hopeit
      - app0-secrets:/app0-admin/.secrets
    environment:
      REDIS_URL: ${REDIS_URL}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_PATH: ${LOGS_PATH}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      APP0_ADMIN_API_URL: ${APP0_ADMIN_API_URL}
      APP0_ADMIN_URL: ${APP0_ADMIN_URL}
      OBJECT_STORAGE_ACCESS_KEY_ID: ${OBJECT_STORAGE_ACCESS_KEY_ID}
      OBJECT_STORAGE_SECRET_ACCESS_KEY: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
      OBJECT_STORAGE_ENDPOINT_URL: ${OBJECT_STORAGE_ENDPOINT_URL}
      OBJECT_STORAGE_SSL: ${OBJECT_STORAGE_SSL}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DOMAIN: ${DOMAIN}
      PYTHONUNBUFFERED: 1
    ports:
      - 8026:8026

  app0-app5-ui:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app5-ui:0.4.6
    ports:
      - '8086:80'
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./conf/app5-ui/default.conf:/etc/nginx/conf.d/default.conf

  app0-app5-job:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app5-job:0.4.6
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app0-log-hopeit:/var/log/hopeit
      - app0-secrets:/app0-admin/.secrets
    environment:
      REDIS_URL: ${REDIS_URL}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_PATH: ${LOGS_PATH}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      APP0_ADMIN_API_URL: ${APP0_ADMIN_API_URL}
      APP0_ADMIN_URL: ${APP0_ADMIN_URL}
      OBJECT_STORAGE_ACCESS_KEY_ID: ${OBJECT_STORAGE_ACCESS_KEY_ID}
      OBJECT_STORAGE_SECRET_ACCESS_KEY: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
      OBJECT_STORAGE_ENDPOINT_URL: ${OBJECT_STORAGE_ENDPOINT_URL}
      OBJECT_STORAGE_SSL: ${OBJECT_STORAGE_SSL}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DOMAIN: ${DOMAIN}
      PYTHONUNBUFFERED: 1
    ports:
      - 8036:8036

  app0-app6-api:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app6:0.2.1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app0-log-hopeit:/var/log/hopeit
      - app0-secrets:/app0-admin/.secrets
    environment:
      REDIS_URL: ${REDIS_URL}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_PATH: ${LOGS_PATH}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      APP0_ADMIN_API_URL: ${APP0_ADMIN_API_URL}
      APP0_ADMIN_URL: ${APP0_ADMIN_URL}
      OBJECT_STORAGE_ACCESS_KEY_ID: ${OBJECT_STORAGE_ACCESS_KEY_ID}
      OBJECT_STORAGE_SECRET_ACCESS_KEY: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
      OBJECT_STORAGE_ENDPOINT_URL: ${OBJECT_STORAGE_ENDPOINT_URL}
      OBJECT_STORAGE_SSL: ${OBJECT_STORAGE_SSL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DOMAIN: ${DOMAIN}
      PYTHONUNBUFFERED: 1
    ports:
      - 8027:8027

  app0-app6-ui:
    image: registry.gitlab.com/ingar-ue/pue-platform/app0-app6-ui:0.3.0
    ports:
      - '8087:80'
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./conf/app6-ui/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  storage1:
  app0-log-hopeit:
  app0-secrets:

networks:
  default:
    name: app0-network
