SYSTEM_USER = "system"
SYSTEM_USER_DESC = "System"
APP_ADMIN = "app0-admin"
APP_APP_CONF_RESOURCE_FOLDER = "conf"
APP_APP_MAILS_RESOURCE_FOLDER = "mails"
APP_APP1 = "App1"
APP_APP1_URL_SUFFIX = "app1"
APP_APP1_RESOURCE_FOLDER = "app1"
APP_APP1_JOB_KEY = "app1-processing-job"
APP_APP2 = "App2"
APP_APP2_URL_SUFFIX = "app2"
APP_APP2_RESOURCE_FOLDER = "app2"
APP_APP2_JOB_KEY = "app2-processing-job"
APP_APP3 = "App3"
APP_APP3_URL_SUFFIX = "app3"
APP_APP3_RESOURCE_FOLDER = "app3"
APP_APP3_JOB_KEY = "app3-processing-job"
APP_APP4 = "App4"
APP_APP4_URL_SUFFIX = "app4"
APP_APP4_RESOURCE_FOLDER = "app4"
APP_APP4_JOB_KEY = "app4-processing-job"
APP_APP5 = "App5"
APP_APP5_URL_SUFFIX = "app5"
APP_APP5_RESOURCE_FOLDER = "app5"
APP_APP5_JOB_KEY = "app5-processing-job"
APP_APP6_RESOURCE_FOLDER = "app6"

# app file types
FILETYPE_GAMS_SOURCE = 'GAMS_SOURCE'
FILETYPE_INPUT_SAMPLE = 'INPUT_SAMPLE'
FILETYPE_OUTPUT_SAMPLE = 'OUTPUT_SAMPLE'

# notifications log entities
OBJECT_CLAIM = "Claim"
OBJECT_EMPLOYEE = "Employee"
OBJECT_SERVICE_PROVIDER = "ServiceProvider"
OBJECT_CLIENT = "Client"
OBJECT_JOB = "Job"

# notifications log types
TYPE_LOG = "log"
TYPE_DIRECT = "direct"
TYPE_UPLOAD = "upload"
TYPE_ERROR = "error"
TYPE_MAIL = "mail"
TYPE_EVENT = "event"
TYPE_STATE_CHANGE = "state-change"
TYPE_ESTIMATION = "estimation"
TYPE_NEGOTIATION = "negotiation"
TYPE_AGREEMENT = "agreement"
TYPE_DECLINE = "decline"
TYPE_JOB = "job"

# job status
STATUS_READY = "READY"
STATUS_RUNNING = "RUNNING"
STATUS_ENDED_OK = "ENDED OK"
STATUS_ENDED_ERROR = "ENDED ERROR"

# job file types
FILETYPE_INPUT = 'INPUT'
FILETYPE_OUTPUT = 'OUTPUT'
FILETYPE_OTHER = 'OTHER'

# scenario status
STATUS_SCENARIO_IN_EVALUATION = "IN EVALUATION"
STATUS_SCENARIO_DISCARDED = "DISCARDED"
STATUS_SCENARIO_APPLIED = "APPLIED"
